In [1]:
import cudf
import os

In [2]:
os.environ["CUDA_VISIBLE_DEVICES"] = "1"

In [3]:
df = cudf.read_csv('/home/ajay/data/census/all_us_block_level_population_census2010/nhgis0014_csv/nhgis0014_ds172_2010_block.csv', usecols=['GISJOIN', 'BLOCKA', 'H7V001', 'STATEA'])

In [19]:
df.H7V001.value_counts()

0        4897539
2         358918
4         240576
3         221282
1         195339
          ...   
7910           1
8634           1
9043           1
9798           1
19352          1
Name: H7V001, Length: 2651, dtype: int32

In [7]:
df.STATEA = df.STATEA.astype('int')

In [8]:
df.GISJOIN = df.GISJOIN.str.replace('G', '').astype('int')

In [9]:
df_temp = df[['GISJOIN', 'H7V001']]
df_temp.index = df_temp.GISJOIN
df_temp = df_temp['H7V001']

In [13]:
df_temp

GISJOIN
1000100201001000      61
1000100201001001       0
1000100201001002       0
1000100201001003      75
1000100201001004       0
                    ... 
72015307506022019    338
72015307506022020      0
72015307506022021      0
72015307506022022      0
72015307506022023      0
Name: H7V001, Length: 11155486, dtype: int64

In [7]:
df.H7V001.describe()

count    1.115549e+07
mean     2.801055e+01
std      7.879496e+01
min      0.000000e+00
25%      0.000000e+00
50%      3.000000e+00
75%      2.800000e+01
max      1.935200e+04
Name: H7V001, dtype: float64

In [3]:
import geopandas as gpd

In [6]:
gpdf = gpd.read_file('/home/ajay/data/census/block_level_population/nhgis0011_shape/nhgis0011_shapefile_tl2010_060_block_2010/CA_block_2010.shp')[['GISJOIN', 'geometry']]

In [5]:
gpdf

STATEFP10 COUNTYFP10 TRACTCE10 BLOCKCE10          GEOID10      NAME10  \
0             06        083    980100      1030  060839801001030  Block 1030   
1             06        083    980100      1047  060839801001047  Block 1047   
2             06        083    980100      1029  060839801001029  Block 1029   
3             06        083    980100      1056  060839801001056  Block 1056   
4             06        083    980100      1021  060839801001021  Block 1021   
...          ...        ...       ...       ...              ...         ...   
708073        06        049    000300      3828  060490003003828  Block 3828   
708074        06        049    000300      1700  060490003001700  Block 1700   
708075        06        049    000300      3901  060490003003901  Block 3901   
708076        06        049    000300      3916  060490003003916  Block 3916   
708077        06        049    000300      3097  060490003003097  Block 3097   

       MTFCC10 UR10 UACE10 UATYP10 FUNCSTAT10    ALAND10  AWATER10  \
0        G5040    R   None    None          S     167769         0   
1        G5040    R   None    None          S  132853658      1257   
2        G5040    R   None    None          S      12286         0   
3        G5040    R   None    None          S       4986         0   
4        G5040    R   None    None          S        455         0   
...        ...  ...    ...     ...        ...        ...       ...   
708073   G5040    R   None    None          S     454283         0   
708074   G5040    R   None    None          S      24331         0   
708075   G5040    R   None    None          S    4263962      1118   
708076   G5040    R   None    None          S   17017083     11948   
708077   G5040    R   None    None          S    5522640     72319   

         INTPTLAT10    INTPTLON10             GISJOIN    Shape_area  \
0       +34.0591019  -120.3358673  G06008309801001030  1.677695e+05   
1       +33.9746147  -120.1477892  G06008309801001047  1.329158e+08   
2       +34.0406847  -120.4588267  G06008309801001029  1.228553e+04   
3       +34.0280957  -120.4437615  G06008309801001056  4.985548e+03   
4       +34.0291854  -120.4598499  G06008309801001021  4.548543e+02   
...             ...           ...                 ...           ...   
708073  +41.2138948  -120.4781221  G06004900003003828  4.542835e+05   
708074  +41.4777745  -120.5829810  G06004900003001700  2.433108e+04   
708075  +41.3311589  -120.5255085  G06004900003003901  4.265079e+06   
708076  +41.2814878  -120.4845384  G06004900003003916  1.702903e+07   
708077  +41.3681603  -120.5480812  G06004900003003097  5.594958e+06   

           Shape_len                                           geometry  
0        3353.624565  MULTIPOLYGON (((-2206015.932 -101657.724, -220...  
1       74313.354262  POLYGON ((-2181405.165 -113455.943, -2181407.1...  
2         541.743249  POLYGON ((-2216942.218 -100327.983, -2216930.8...  
3         349.108823  MULTIPOLYGON (((-2215789.478 -102240.909, -221...  
4          87.909874  POLYGON ((-2217294.630 -101627.956, -2217296.2...  
...              ...                                                ...  
708073   3355.148312  POLYGON ((-2013834.111 677502.782, -2013833.37...  
708074   1079.060162  POLYGON ((-2014863.407 707671.049, -2014877.58...  
708075  11147.050455  POLYGON ((-2014109.689 690017.362, -2014128.76...  
708076  18376.625122  POLYGON ((-2010263.833 682849.289, -2010253.80...  
708077  24086.152443  POLYGON ((-2013680.321 700026.421, -2013668.26...  

[708078 rows x 19 columns]

In [195]:
gpdf.GISJOIN = gpdf.GISJOIN.str.replace('G', '').astype('int')

In [196]:
gpdf.head()

GISJOIN                                           geometry
0  6008309801001030  MULTIPOLYGON (((-2206015.932 -101657.724, -220...
1  6008309801001047  POLYGON ((-2181405.165 -113455.943, -2181407.1...
2  6008309801001029  POLYGON ((-2216942.218 -100327.983, -2216930.8...
3  6008309801001056  MULTIPOLYGON (((-2215789.478 -102240.909, -221...
4  6008309801001021  POLYGON ((-2217294.630 -101627.956, -2217296.2...

In [84]:
type(gpdf.loc[0].geometry)

shapely.geometry.multipolygon.MultiPolygon

In [269]:
import random
######
def random_points_in_polygon(number, polygon):
    points_x = np.array(0,)
    points_y = np.array(0,)
    min_x, min_y, max_x, max_y = polygon.bounds
    i= 0
    while i < number:
        point_x = random.uniform(min_x, max_x)
        point_y = random.uniform(min_y, max_y)
        if polygon.contains(Point(point_x, point_y)):
            points_x = np.append(points_x, point_x)
            points_y = np.append(points_y, point_y)
            i += 1
    return points_x, points_y  # returns list of shapely point
######


In [256]:
df_final = cudf.DataFrame()

In [345]:
from numba import jit

In [350]:
@jit(nopython=False)
def generate_data():
    t1 = datetime.datetime.now()
    gis_index_df = df_temp.index.to_array()
    final_points_x = np.array(0,)
    final_points_y = np.array(0,)
    gisjoin = np.array(0,)

    for index, row in gpdf.iterrows():
        points_x = np.array(0,)
        points_y = np.array(0,)
        gisjoin_temp = np.array(0,)
        if row['GISJOIN'] in gis_index_df and df_temp.loc[row['GISJOIN']]>0:
            num_points = df_temp.loc[row['GISJOIN']]
            polygon = row['geometry']
            points_x, points_y = random_points_in_polygon(num_points, polygon)
            gisjoin_temp = np.array([row['GISJOIN']]*len(points_x))
            gisjoin = np.append(gisjoin, gisjoin_temp)
            final_points_x = np.append(final_points_x, points_x)
            final_points_y = np.append(final_points_y, points_y)
            print('', end='\r')
            print('Percent', "{0:0.2f}".format((index/len(gpdf))*100), '%', end='')
    print('total time', datetime.datetime.now() - t1)
    
    return cudf.DataFrame({'GISJOIN': gisjoin,'x': final_points_x, 'y':final_points_y})

In [351]:
generate_data()

ImportError: cannot import name 'enumdecl' from 'numba.typing' (/home/ajay/anaconda3/envs/rapids_dev_0.12/lib/python3.7/site-packages/numba/typing/__init__.py)

In [9]:
import numpy as np

In [17]:
states = {
55:"WI",
56:"WY"
}
state_key_list = list(states.keys())

In [18]:
state_key_list.reverse()
state_key_list

[56, 55]

In [328]:
final_points_y

array([      0.        ,       0.        , -118565.88877688,
       -113889.41198673, -112753.6630583 , -111191.11363606])

In [324]:
final_points_x

array([       0.        ,        0.        , -2193922.69369754,
       -2187728.33411837, -2192216.45169422, -2188394.79131228])

In [325]:
gisjoin

array([               0, 6008309801001047, 6008309801001047,
       6008309801001047, 6008309801001047, 6008309801001047])

In [332]:
df = cudf.DataFrame({'GISJOIN': gisjoin,'x': final_points_x, 'y':final_points_y})

In [334]:
df.to_csv('test_file.csv')

In [285]:
import datetime

In [287]:
t1 = datetime.datetime.now()
print('total time', datetime.datetime.now() - t1)

total time 0:00:00.000071


In [258]:
np.append(np.array([1]),2)

array([1, 2])

In [220]:
len(final_points_x)

5008962

In [191]:
df_temp

GISJOIN  H7V001
0       6000104001001000       0
1       6000104001001001       0
2       6000104001001002       0
3       6000104001001003       0
4       6000104001001004       0
...                  ...     ...
710140  6011500411004062      12
710141  6011500411004063       0
710142  6011500411004064       2
710143  6011500411004065       3
710144  6011500411004066       3

[710145 rows x 2 columns]

In [181]:
for index in df_temp:
    print(index)

GISJOIN
H7V001


In [163]:
for i in df_temp.GISJOIN:
    lat, long, p_id = [],[],[]
    if i in gpdf.GISJOIN and :
        

G06000104001001000


In [152]:
d[0].y

-101393.64633179616

In [123]:
t = gpd.GeoSeries(d)

In [129]:
t[t.within(poly)].geometry

0     POINT (-2207442.891 -98966.212)
1    POINT (-2205332.869 -101273.168)
2    POINT (-2205413.359 -101396.469)
3    POINT (-2205184.338 -101656.963)
4    POINT (-2205111.674 -101494.466)
5    POINT (-2205188.718 -101386.087)
6     POINT (-2208009.936 -98918.525)
7    POINT (-2205409.674 -101485.571)
8    POINT (-2205479.328 -101248.083)
9    POINT (-2205224.513 -101602.188)
dtype: geometry

In [81]:
gdf_points

0     POINT (-2206449.744 -100947.146)
1      POINT (-2205637.402 -99773.893)
2     POINT (-2205441.734 -101392.341)
3     POINT (-2207624.627 -101543.755)
4      POINT (-2207318.230 -99668.328)
                    ...               
95     POINT (-2206434.777 -98960.404)
96    POINT (-2207234.191 -101250.714)
97    POINT (-2207876.768 -100969.751)
98    POINT (-2205450.276 -100616.898)
99    POINT (-2205460.360 -101259.451)
Length: 100, dtype: geometry

In [77]:
# only keep those points within polygons
gdf_points = gdf_points[gdf_points.within(gpdf.loc[0])]

TypeError: (<class 'geopandas.geoseries.GeoSeries'>, <class 'pandas.core.series.Series'>)

In [27]:
df.H7V001

0          0
1          0
2          0
3          0
4          0
          ..
710140    12
710141     0
710142     2
710143     3
710144     3
Name: H7V001, Length: 710145, dtype: int64

In [71]:
gpdf.BLOCKCE10 = gpdf.BLOCKCE10.astype('int')

In [78]:
t1 = gpdf.BLOCKCE10.unique()

In [82]:
t1 =np.sort(t1)

In [52]:
import numpy as np

In [ ]:
temp = []
for i in t1:
    if i not in t:
        temp.append(i)

In [ ]:
len(temp)